'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import {usePathname} from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentRoute = usePathname();
  const stylehref='flex items-center pl-[30px] pr-[30px] h-full no-underline';
  const active = stylehref + ' text-black bg-amber-300';
  const inactive = stylehref+ ' text-white';
  console.log(currentRoute);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='h-[56px] flex justify-center items-center bg-indigo-700 drop-shadow-lg'>
          <Link href='/' className={ (currentRoute === '/') ? active : inactive}> HOME </Link>
          <Link href='/about'  className={ (currentRoute === '/about') ? active : inactive}> ACERCA DE </Link>
          <Link href='/contactos'  className={ (currentRoute === '/contactos') ? active : inactive}> CONTACTOS </Link>
        </nav>

        {children}</body>
    </html>
  )
}